export const SERVICES = {
  stores: { slug: 'stores', name: 'prcat.svc.stores', icon: '🛒' },
  restaurants: { slug: 'restaurants', name: 'prcat.svc.restaurants', icon: '🍽️' },
  hotels: { slug: 'hotels', name: 'prcat.svc.hotels', icon: '🏨' },
  flights: { slug: 'flights', name: 'prcat.svc.flights', icon: '✈️' },
  travel_offices: { slug: 'travel_offices', name: 'prcat.svc.travel_offices', icon: '🧳' },
};

export const ROOM_TYPES = {
  standard: 'prcat.room.standard',
  family: 'prcat.room.family',
  deluxe: 'prcat.room.deluxe',
  suite: 'prcat.room.suite',
  presidential: 'prcat.room.presidential',
};

export const CATALOGS = {
  stores: {
    api: '/provider/products',
    itemType: 'products',
    categoriesApi: '/provider/product-categories',
    title: 'prcat.stores.title',
    item: 'prcat.stores.item',
    itemF: 'prcat.stores.itemF',
    icon: '🛍️',
    subtitle: 'prcat.stores.subtitle',
    columns: [
      { key: 'name_ar', label: 'prcat.stores.colProduct' },
      { key: 'category_name', label: 'prcat.stores.colCategory' },
      { key: 'price', label: 'prcat.col.price', money: true },
      { key: 'old_price', label: 'prcat.stores.colOldPrice', money: true },
      { key: 'stock', label: 'prcat.stores.colStock' },
      { key: 'is_featured', label: 'prcat.col.featured' },
      { key: 'is_active', label: 'prcat.col.status' },
    ],
    fields: [
      { key: 'name_ar', label: 'prcat.stores.fieldName', required: true },
      { key: 'name_en', label: 'prcat.field.nameEn' },
      { key: 'category_id', label: 'prcat.stores.fieldCategory', type: 'select', fromCategories: true },
      { key: 'price', label: 'prcat.col.price', type: 'number', required: true },
      { key: 'old_price', label: 'prcat.stores.fieldOldPrice', type: 'number', hint: 'prcat.stores.hintOldPrice' },
      { key: 'stock', label: 'prcat.stores.colStock', type: 'number' },
      { key: 'images_json', label: 'prcat.field.images', type: 'images', hint: 'prcat.hint.images' },
      { key: 'description', label: 'prcat.field.description', type: 'textarea' },
      { key: 'is_featured', label: 'prcat.stores.fieldFeatured', type: 'checkbox' },
      { key: 'is_active', label: 'prcat.stores.fieldActive', type: 'checkbox' },
    ],
  },

  restaurants: {
    api: '/provider/menu-items',
    itemType: 'menu_items',
    categoriesApi: '/provider/menu-categories',
    title: 'prcat.restaurants.title',
    item: 'prcat.restaurants.item',
    itemF: 'prcat.restaurants.itemF',
    icon: '🍽️',
    subtitle: 'prcat.restaurants.subtitle',
    columns: [
      { key: 'name_ar', label: 'prcat.restaurants.colItem' },
      { key: 'category_name', label: 'prcat.restaurants.colCategory' },
      { key: 'price', label: 'prcat.col.price', money: true },
      { key: 'is_available', label: 'prcat.restaurants.colAvailable' },
      { key: 'is_featured', label: 'prcat.col.featured' },
      { key: 'is_active', label: 'prcat.col.status' },
    ],
    fields: [
      { key: 'name_ar', label: 'prcat.restaurants.fieldName', required: true },
      { key: 'name_en', label: 'prcat.field.nameEn' },
      { key: 'category_id', label: 'prcat.restaurants.fieldCategory', type: 'select', fromCategories: true },
      { key: 'price', label: 'prcat.col.price', type: 'number', required: true },
      { key: 'images_json', label: 'prcat.field.images', type: 'images', hint: 'prcat.hint.images' },
      { key: 'description', label: 'prcat.field.description', type: 'textarea' },
      { key: 'is_available', label: 'prcat.restaurants.fieldAvailable', type: 'checkbox' },
      { key: 'is_featured', label: 'prcat.restaurants.fieldFeatured', type: 'checkbox' },
      { key: 'is_active', label: 'prcat.field.active', type: 'checkbox' },
    ],
  },

  hotels: {
    api: '/provider/rooms',
    itemType: 'hotel_rooms',
    title: 'prcat.hotels.title',
    item: 'prcat.hotels.item',
    itemF: 'prcat.hotels.itemF',
    icon: '🏨',
    subtitle: 'prcat.hotels.subtitle',
    columns: [
      { key: 'name_ar', label: 'prcat.hotels.colRoom' },
      { key: 'room_type', label: 'prcat.hotels.colType', roomType: true },
      { key: 'price_per_night', label: 'prcat.hotels.colPricePerNight', money: true },
      { key: 'max_guests', label: 'prcat.hotels.colGuests' },
      { key: 'is_featured', label: 'prcat.col.featured' },
      { key: 'is_active', label: 'prcat.col.status' },
    ],
    fields: [
      { key: 'name_ar', label: 'prcat.hotels.fieldName', required: true },
      { key: 'name_en', label: 'prcat.field.nameEn' },
      { key: 'room_type', label: 'prcat.hotels.fieldRoomType', type: 'select', options: ROOM_TYPES },
      { key: 'price_per_night', label: 'prcat.hotels.fieldPricePerNight', type: 'number', required: true },
      { key: 'max_guests', label: 'prcat.hotels.fieldMaxGuests', type: 'number' },
      { key: 'images_json', label: 'prcat.field.images', type: 'images', hint: 'prcat.hint.images' },
      { key: 'description', label: 'prcat.field.description', type: 'textarea' },
      { key: 'is_featured', label: 'prcat.hotels.fieldFeatured', type: 'checkbox' },
      { key: 'is_active', label: 'prcat.field.active', type: 'checkbox' },
    ],
  },

  flights: {
    api: '/provider/flights',
    itemType: 'flights',
    title: 'prcat.flights.title',
    item: 'prcat.flights.item',
    itemF: 'prcat.flights.itemF',
    icon: '✈️',
    subtitle: 'prcat.flights.subtitle',
    columns: [
      { key: 'flight_number', label: 'prcat.flights.colFlightNumber' },
      { key: 'airline', label: 'prcat.flights.colAirline' },
      { key: 'route', label: 'prcat.flights.colRoute', route: true },
      { key: 'departure_at', label: 'prcat.flights.colDeparture', datetime: true },
      { key: 'price', label: 'prcat.col.price', money: true },
      { key: 'seats', label: 'prcat.flights.colSeats' },
      { key: 'is_featured', label: 'prcat.col.featured' },
      { key: 'is_active', label: 'prcat.col.status' },
    ],
    fields: [
      { key: 'flight_number', label: 'prcat.flights.fieldFlightNumber' },
      { key: 'airline', label: 'prcat.flights.fieldAirline' },
      { key: 'origin', label: 'prcat.flights.fieldOriginCode', hint: 'prcat.flights.hintOriginCode' },
      { key: 'origin_ar', label: 'prcat.flights.fieldOrigin' },
      { key: 'destination', label: 'prcat.flights.fieldDestCode', hint: 'prcat.flights.hintDestCode' },
      { key: 'destination_ar', label: 'prcat.flights.fieldDestination' },
      { key: 'departure_at', label: 'prcat.flights.fieldDepartureTime', type: 'datetime', required: true },
      { key: 'arrival_at', label: 'prcat.flights.fieldArrivalTime', type: 'datetime' },
      { key: 'price', label: 'prcat.flights.fieldPrice', type: 'number', required: true },
      { key: 'seats', label: 'prcat.flights.fieldSeats', type: 'number' },
      { key: 'is_featured', label: 'prcat.flights.fieldFeatured', type: 'checkbox' },
      { key: 'is_active', label: 'prcat.field.active', type: 'checkbox' },
    ],
  },

  travel_offices: {
    api: '/provider/packages',
    itemType: 'travel_packages',
    title: 'prcat.travel.title',
    item: 'prcat.travel.item',
    itemF: 'prcat.travel.itemF',
    icon: '🧳',
    subtitle: 'prcat.travel.subtitle',
    columns: [
      { key: 'name_ar', label: 'prcat.travel.colPackage' },
      { key: 'destination', label: 'prcat.travel.colDestination' },
      { key: 'duration_days', label: 'prcat.travel.colDays' },
      { key: 'price', label: 'prcat.col.price', money: true },
      { key: 'is_featured', label: 'prcat.col.featured' },
      { key: 'is_active', label: 'prcat.col.status' },
    ],
    fields: [
      { key: 'name_ar', label: 'prcat.travel.fieldName', required: true },
      { key: 'name_en', label: 'prcat.field.nameEn' },
      { key: 'destination', label: 'prcat.travel.fieldDestination' },
      { key: 'duration_days', label: 'prcat.travel.fieldDays', type: 'number' },
      { key: 'price', label: 'prcat.col.price', type: 'number', required: true },
      { key: 'includes_json', label: 'prcat.travel.fieldIncludes', type: 'lines', hint: 'prcat.travel.hintIncludes' },
      { key: 'images_json', label: 'prcat.field.images', type: 'images', hint: 'prcat.hint.images' },
      { key: 'description', label: 'prcat.field.description', type: 'textarea' },
      { key: 'is_featured', label: 'prcat.travel.fieldFeatured', type: 'checkbox' },
      { key: 'is_active', label: 'prcat.field.active', type: 'checkbox' },
    ],
  },
};

export const CATEGORY_CONFIG = {
  stores: { api: '/provider/product-categories', title: 'prcat.cat.stores.title', item: 'prcat.cat.stores.item', icon: '🗂️' },
  restaurants: { api: '/provider/menu-categories', title: 'prcat.cat.restaurants.title', item: 'prcat.cat.restaurants.item', icon: '🗂️' },
};

export const CATEGORY_FIELDS = [
  { key: 'name_ar', label: 'prcat.catfield.nameAr', required: true },
  { key: 'name_en', label: 'prcat.field.nameEn' },
  { key: 'icon', label: 'prcat.catfield.icon' },
  { key: 'sort_order', label: 'prcat.catfield.sortOrder', type: 'number' },
  { key: 'is_active', label: 'prcat.field.active', type: 'checkbox' },
];
